FROM ubuntu:bionic

# Install basic build tools:
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes build-essential git curl

# Install nodejs:
RUN curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
RUN echo "deb https://deb.nodesource.com/node_14.x bionic main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes nodejs

# Copy in the code and fixed entrypoint script
COPY ./colte /colte
COPY ./docker-entrypoint.sh /colte/docker-entrypoint.sh

WORKDIR /colte

RUN make get_nfpm

ENTRYPOINT ["/colte/docker-entrypoint.sh", "bionic"]